### ISSUE TITLE
What?Very Odd;

### ISSUE THREAD

**Issue by Kilo-411** [blackcodercrush/hack-facebook-teman#1]
I never leave an issue on someones work but this thing here has lost me.
I mean you are assigning varibles on every thing and rhats still aint what gets me.. Its Nano. You put nano on it.. Im interested cause i guess its to install the app or make dir.. But the whole thing has me bazzeled . but if it works it works .. I will pipe it in.later

**Comment by jandacantik** [comment]
Tercompile :v
Sampahh
https://pastebin.com/3rYwQgeG

**Comment by gellmoxer** [comment]
Kayaknya gak terlalu ngerti b. Pemrograman.. Itu di def super,  Var pass tambahan, stringnya buat pw.. Mana mungkin work :v
